### ISSUE TITLE
Mux doesnt support latest Exoplayer releases

### ISSUE THREAD

**Issue by Jogan** [muxinc/stats-sdk-exoplayer#4]
Tried using Mux with latest Exoplayer r2.4.4 and the bleeding edge r2.5.0-beta1 version. Looks like Mux hasnt been updated to support Exoplayer past r2.1.1. Exoplayer has since been updated considerably. 

I noticed one breaking change to Mux with the renaming of StreamingDrmSessionManager to DefaultDrmSessionManager in Exoplayer r2.2.0 but there are probably more.

**Comment by jsanford8** [comment]
Hi John - Have you tried the r2.4.1 AAR which can be found on the [releases page](https://github.com/muxinc/stats-sdk-exoplayer/releases)? We try to stay up to date with the ExoPlayer releases as much as we can, but sometimes we fall a little behind. 

ExoPlayer's breaking changes they make in minor version bumps make it a little bit tricky, but we strive to have at least a release for every minor version release that they do. We likely won't release a version specifically for r2.5.0 until they release it.

Let me know if you're still having trouble!

**Comment by Jogan** [comment]
@jsanford8 been away a few days sorry for late response. I am using Exoplayer v2.5.0 which hasn't been officially released. Looks like the breaking change is caused by the `EventListener.class` being moved under `Player.class` instead of `Exoplayer.class`. Will revert back to 2.4.4 for now and wait until official release. Thanks!

**Comment by Jogan** [comment]
@jsanford8 Any estimation on when support for ExoPlayer 2.5.1 will be added?

**Comment by Jogan** [comment]
@jsanford8 any updates?

**Comment by jsanford8** [comment]
This was just released.
